import test from 'node:test';
import assert from 'node:assert/strict';
import {inspectFormTemplates,uploadFormTemplate,reviewChildPrint,startChildPrintBatch,refreshDocumentReceipt,validNativePdfUrl,templateListPath} from './documents.mjs';
import {nativeFormRequest} from './native-transport.mjs';
import {UAT_ORIGIN,FORM_PATH} from './capture.mjs';
const schema='9d10200e-a554-4e3e-84ed-47e5a60bfc6d',operationId='a1234567-1234-1234-1234-123456789abc',jobId='b1234567-1234-1234-1234-123456789abc';
const base64=Buffer.from([80,75,3,4,1,2]).toString('base64');
function server() {
 const receipts=new Map(),calls=[],templates=[{id:3,template_name:'Standard',entity_type:'form',entity_id:null,is_ac_template:true,is_default:true},{id:63,template_name:'Entry.docx',entity_type:'form',entity_id:schema}];
 const children=[{id:142,form_id:100,parent_submission_id:141},{id:143,form_id:100,parent_submission_id:141}];
 const io={load:async id=>structuredClone(receipts.get(id)),save:async(id,r)=>receipts.set(id,structuredClone(r)),request:async(method,path,body)=>{
  calls.push({method,path,body});
  if(path===`${FORM_PATH}/100`) return {id:100,name:'Entries',schema_id:schema};
  if(path===templateListPath(schema))return {items:structuredClone(templates),total_pages:1};
  if(path.endsWith('?with_subforms=true'))return {id:141,subforms:structuredClone(children)};
  if(path.endsWith('/start_print_job'))return {print_job_id:jobId};
  if(path.startsWith('/api/v1/printing/jobs/'))return {status:'SUCCESS',result:`${UAT_ORIGIN}/api/v1/files/tasks/form_submissions/${jobId}.pdf`};
  if(path==='/api/v1/tasks/custom_templates'&&method==='POST'){const result={id:64,entity_type:'form',entity_id:schema,template_name:body.fileName};templates.push(result);return result;}
  throw new Error('Unexpected request');
 }};return {io,receipts,calls,templates,children};
}
test('upload uses the schema identity, verifies ownership and refuses replay',async()=>{const {io,calls}=server();const input={operationId,formId:100,schemaId:schema,fileName:'Entry.docx',base64};const receipt=await uploadFormTemplate(input,io);assert.equal(receipt.status,'verified');assert.equal(receipt.templateId,64);assert.equal(calls.find(x=>x.method==='POST').body.schemaId,schema);await assert.rejects(uploadFormTemplate(input,io),/already has a receipt/);});
test('changed upload target and bad files stop before writes',async()=>{const {io,calls}=server();await assert.rejects(uploadFormTemplate({operationId,formId:100,schemaId:operationId,fileName:'Entry.docx',base64},io),/changed/);await assert.rejects(uploadFormTemplate({operationId,formId:100,schemaId:schema,fileName:'../Entry.docx',base64},io),/Word/);assert(!calls.some(x=>x.method==='POST'));});
test('upload uncertainty is recorded before POST and never replayed',async()=>{const {io,receipts}=server(),request=io.request;io.request=async(m,p,b)=>{if(m==='POST'){assert.equal(receipts.get(operationId).status,'running');throw new Error('Timeout');}return request(m,p,b);};const input={operationId,formId:100,schemaId:schema,fileName:'Entry.docx',base64};assert.equal((await uploadFormTemplate(input,io)).status,'partial');await assert.rejects(uploadFormTemplate(input,io),/receipt/);});
test('review strips answers, deduplicates form lookups and rejects unrelated children',async()=>{const {io,calls,children}=server();children[0].fields=[{field_value:'Private answer'}];const review=await reviewChildPrint(141,io.request);assert.equal(review.entries.length,2);assert(!JSON.stringify(review).includes('Private'));assert.equal(calls.filter(x=>x.path===`${FORM_PATH}/100`).length,1);children[1].parent_submission_id=999;await assert.rejects(reviewChildPrint(141,io.request),/unrelated/);});
test('batch binds templates to each child, verifies changes and polls existing jobs only',async()=>{const {io,calls}=server(),review=await reviewChildPrint(141,io.request);const input={operationId,parentSubmissionId:141,digest:review.digest,choices:review.entries.map(entry=>({submissionId:entry.submissionId,templateId:63}))};const receipt=await startChildPrintBatch(input,io);assert.equal(receipt.jobs.length,2);assert.equal(receipt.status,'running');assert.equal((await refreshDocumentReceipt(operationId,io)).status,'verified');assert.equal(calls.filter(x=>x.method==='POST').length,2);await assert.rejects(startChildPrintBatch(input,io),/already has a receipt/);await refreshDocumentReceipt(operationId,io);assert.equal(calls.filter(x=>x.path.startsWith('/api/v1/printing/jobs/')).length,2);});
test('batch rejects stale review and foreign or duplicate template selections without starting jobs',async()=>{const {io,calls,children}=server(),review=await reviewChildPrint(141,io.request);const input={operationId,parentSubmissionId:141,digest:review.digest,choices:[{submissionId:142,templateId:999},{submissionId:143,templateId:63}]};await assert.rejects(startChildPrintBatch(input,io),/does not belong/);input.choices=[{submissionId:142,templateId:63},{submissionId:142,templateId:63}];await assert.rejects(startChildPrintBatch(input,io),/one template/);children.pop();await assert.rejects(startChildPrintBatch(input,io),/changed/);assert(!calls.some(x=>x.method==='POST'));});
test('partial batch stops after an uncertain start and keeps the known job for refresh',async()=>{const {io,receipts,calls}=server(),review=await reviewChildPrint(141,io.request),request=io.request;io.request=async(m,p,b)=>{if(m==='POST'&&p.includes('/143/')){assert.equal(receipts.get(operationId).jobs[1].status,'starting');throw new Error('Timeout');}return request(m,p,b);};const receipt=await startChildPrintBatch({operationId,parentSubmissionId:141,digest:review.digest,choices:[{submissionId:142,templateId:63},{submissionId:143,templateId:63}]},io);assert.equal(receipt.status,'partial');assert.equal(receipt.jobs[1].status,'uncertain');const refreshed=await refreshDocumentReceipt(operationId,io);assert.equal(refreshed.status,'partial');assert.equal(refreshed.jobs[0].status,'ready');assert.equal(calls.filter(x=>x.method==='POST').length,1);});
test('print results never link outside the verified native PDF path',()=>{assert(validNativePdfUrl(`${UAT_ORIGIN}/api/v1/files/tasks/form_submissions/${jobId}.pdf`));assert(!validNativePdfUrl('https://other.example/file.pdf'));assert(!validNativePdfUrl(`${UAT_ORIGIN}/api/v1/files/tasks/form_submissions/${jobId}.pdf?token=secret`));});
test('native transport keeps draft writes on settings and uses multipart without reading credentials',async()=>{const calls=[],host={location:{origin:UAT_ORIGIN,hash:'#/system-settings/forms'},jQuery:{ajax:async options=>{calls.push(options);return {id:64};}}};await nativeFormRequest('POST','/api/v1/tasks/custom_templates',{documentUpload:true,fileName:'Entry.docx',base64,schemaId:schema},host);assert.equal(calls[0].contentType,false);assert.equal(calls[0].processData,false);assert.equal(calls[0].data.get('entity_id'),schema);assert.equal(calls[0].data.get('template_file').name,'Entry.docx');await nativeFormRequest('GET',templateListPath(schema),undefined,host);await nativeFormRequest('GET','/api/v1/tasks/forms20/submissions/141?with_subforms=true',undefined,host);host.location.hash='#/dashboard/client-forms/141';await nativeFormRequest('POST','/api/v1/tasks/forms20/submissions/142/start_print_job',{template_id:63},host);await assert.rejects(nativeFormRequest('POST',FORM_PATH,{},host),/only manages/);await assert.rejects(nativeFormRequest('POST','/api/v1/tasks/forms20/submissions/142/start_print_job',{template_id:63,approve:true},host),/template ID/);await assert.rejects(nativeFormRequest('GET','/api/v1/tasks/custom_templates?entity_type=form&entity_id='+schema+'&all=true',undefined,host),/only manages/);host.location.origin='https://other.alayacare.ca';await assert.rejects(nativeFormRequest('GET',`${FORM_PATH}/100`,undefined,host),/Northern Health/);});
